List<String> Race_Selector = [
  '-Seleccionar-',
  "Abisinio", 
  "Americano de pelo corto", 
  "Angora turco", 
  "Azul ruso", 
  "Bengala", 
  "Birmano", 
  "Bombay", 
  "Britanico de pelo corto", 
  "Cornish rex", "Devon rex", 
  "Domestico", "Esfinge", 
  "Habana", "Javanes", 
  "Korat", "Maine Coon", 
  "Manx", "Mau Egipcio", 
  "Noruego", "Ocicat", 
  "Oriental", "Persa", 
  "Peterbald", "Ragdoll", 
  "Sagrado de Birmania", 
  "Savannah", "Siames", 
  "Singapur", "Somali", 
  "Sphynx", "Tonkies", 
  "Turco de Van", 
  "York de Chocolate", 
  "Otros"
];